name: jenkins image build and push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    #制作docker镜像推送到dockerhub
    - name: build and push to dockerhub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        docker image build -t my-jenkins:latest .
        docker tag my-jenkins:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-jenkins:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-jenkins:latest
